services:
  frontend:
    container_name: frontend
    ports:
      - '8001:8001'
    volumes: # Needed to fix issues with vite and optional dependencies in NPM
      - /srv/www/node_modules
      - /srv/www/.svelte-kit
    depends_on:
      - backend
  backend:
    container_name: backend
    ports:
      - '9000:9000'
    volumes: # Needed to fix issues with vite and optional dependencies in NPM
      - /srv/www/vendor
      - /srv/www/node_modules
    depends_on:
      - redis
      - python_backend
    environment:
      - DB_PW=
      - DB_HOST=redis # Internal
      - DB_PORT=6379 # Internal
      - DB_ID=0
      - TEMP_DIR=/tmp/
      - 'PHP_BACKEND_URL=http://localhost:8080/api/' # External
      - 'PYTHON_BACKEND_URL=http://python_backend:8000/' # Internal
      - 'GO_BACKEND_URL=http://host.containers.internal:8090/' # External # TODO: FIXME: Put Go in container
      - TOUTV_EMAIL=
      - TOUTV_PASSWORD=
  python_backend:
    container_name: python_backend
    ports:
      - '8000:8000'
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
