name: abcmovies

services:
  dev:
    build:
      target: dev
    container_name: dev
    env_file:
      - config/.env
    ports:
      - '8080:7331'
    # podman doesn't support watch
    # Sync modified files to rebuild app
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /usr/src/app
    #     # Rebuild container if config or deps files changed
    #     - action: rebuild
    #       path: go.mod
    #     - action: rebuild
    #       path: go.sum
    #     - action: rebuild
    #       path: config/air/*.toml
    volumes:
      - "./:/usr/src/app"
    profiles: [ dev ]

  prod:
    build:
      target: prod
    container_name: prod
    env_file:
      - config/.env
    ports:
      - '8080:80'
    restart: unless-stopped
    profiles: [ prod ]

  testing:
    build:
      target: testing
    container_name: testing
    env_file:
      - config/.env
    profiles: [ testing ]
