services:
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
      target: frontend-prod
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
      target: backend-prod
  python_backend:
    build:
      context: src/python-backend
      dockerfile: Dockerfile
      target: python-backend-prod
