services:
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile-prod
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile-prod
  python_backend:
    build:
      context: src/python-backend
      dockerfile: Dockerfile-prod
