services:
  frontend:
    container_name: frontend
    ports:
      - "8002:8001"
    volumes: # Needed to fix issues with vite and optional dependencies in NPM
      - /srv/www/node_modules
      - /srv/www/.svelte-kit
    depends_on:
      # - backend # backend
      - go_backend
    networks:
      - nginx-adjacent

  # backend:
  #   container_name: backend # backend
  #   ports:
  #     - "9000:9000"
  #   volumes: # Needed to fix issues with vite and optional dependencies in NPM
  #     - /srv/www/vendor
  #     - /srv/www/node_modules
  #   depends_on:
  #     - redis
  #     - python_backend
  #   environment:
  #     - DB_HOST=redis # Internal
  #     - DB_PORT=6379 # Internal
  #     - DB_ID=0
  #     - TEMP_DIR=/tmp/
  #     - "PHP_BACKEND_URL=http://localhost:8080/api/" # External
  #     - "PYTHON_BACKEND_URL=http://python_backend:8000/" # Internal
  #     - "GO_BACKEND_URL=http://host.docker.internal:8090/api/" # External
  #   env_file:
  #     - .env
  #   networks:
  #     - nginx-adjacent
  #     - python-adjacent
  #     - redis-adjacent

  python_backend:
    container_name: python_backend
    ports:
      - "8008:8000"
    networks:
      - python-adjacent

  go_backend:
    container_name: go_backend
    ports:
      - "8090:8090"
    networks:
      - nginx-adjacent
      - redis-adjacent

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6380:6379" # 6379
    networks:
      - nginx-adjacent

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-base
    ports:
      - "8080:80"
    depends_on:
      - frontend
      # - backend # backend
    networks:
      - nginx-adjacent

networks:
  nginx-adjacent:
    name: nginx-adjacent
  python-adjacent:
    name: python-adjacent
  redis-adjacent:
    name: redis-adjacent
