services:
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
      target: frontend-dev
    volumes:
      - type: bind
        source: ./src/frontend
        target: /srv/www
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
      target: go-backend-dev
  volumes:
    - type: bind
      source: ./src/backend
      target: /srv/www
