server {
    listen 80;
    server_name ABCMovies;
    
    location / {
        proxy_pass http://frontend/;
    }

    location /api/ {

        proxy_set_header X-Forwarded-Proto $host;
        proxy_set_header X-Forwarded-Host $remote_addr;

        fastcgi_pass http://backend:9000/;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param QUERY_STRING $query_string;

        if (!-e $request_filename){
          rewrite ^(.*)$ /index.php break;
        }
    }

}