// Code generated by ogen, DO NOT EDIT.
package oas

type GetEpisodeByIdRes interface {
	getEpisodeByIdRes()
}

type GetEpisodeStreamFileRes interface {
	getEpisodeStreamFileRes()
}

type GetEpisodeStreamsRes interface {
	getEpisodeStreamsRes()
}

type GetEpisodeSubtitleFileRes interface {
	getEpisodeSubtitleFileRes()
}

type GetEpisodeSubtitlesRes interface {
	getEpisodeSubtitlesRes()
}

type GetEpisodeThumbnailRes interface {
	getEpisodeThumbnailRes()
}

type GetEpisodesRes interface {
	getEpisodesRes()
}

type GetMovieBackdropRes interface {
	getMovieBackdropRes()
}

type GetMovieByIdRes interface {
	getMovieByIdRes()
}

type GetMoviePosterRes interface {
	getMoviePosterRes()
}

type GetMovieStreamFileRes interface {
	getMovieStreamFileRes()
}

type GetMovieStreamsRes interface {
	getMovieStreamsRes()
}

type GetMovieSubtitleFileRes interface {
	getMovieSubtitleFileRes()
}

type GetMovieSubtitlesRes interface {
	getMovieSubtitlesRes()
}

type GetMoviesRes interface {
	getMoviesRes()
}

type GetSeasonBackdropRes interface {
	getSeasonBackdropRes()
}

type GetSeasonByIdRes interface {
	getSeasonByIdRes()
}

type GetSeasonPosterRes interface {
	getSeasonPosterRes()
}

type GetSeasonsRes interface {
	getSeasonsRes()
}

type GetSeriesBackdropRes interface {
	getSeriesBackdropRes()
}

type GetSeriesByIdRes interface {
	getSeriesByIdRes()
}

type GetSeriesPosterRes interface {
	getSeriesPosterRes()
}

type GetSeriesRes interface {
	getSeriesRes()
}

type GetServiceByTagRes interface {
	getServiceByTagRes()
}

type GlobalSearchRes interface {
	globalSearchRes()
}
