// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// A single episode within a TV series season. Maps to schema.org [TVEpisode].
//
// [TVEpisode]: https://schema.org/TVEpisode
// Ref: #/components/schemas/Episode
type Episode struct {
	// JSON-LD type discriminator.
	Type EpisodeType `json:"@type"`
	// Canonical API identifier.
	ID string `json:"id"`
	// Sequential episode number within the season.
	EpisodeNumber int `json:"episodeNumber"`
	// Episode title.
	Name string `json:"name"`
	// Synopsis or plot summary.
	Description OptString `json:"description"`
	// Original air or release date (ISO 8601 / RFC 3339 full-date).
	DatePublished OptDate `json:"datePublished"`
	// Runtime in ISO 8601 duration format.
	Duration string `json:"duration"`
	// ISO 3166-1 alpha-2 country code of origin.
	CountryOfOrigin OptString `json:"countryOfOrigin"`
	// ISO 639-1 language codes available for this episode.
	Languages []string `json:"languages"`
	// URL to the episode's poster image.
	Poster OptURI `json:"poster"`
	// Content rating (e.g. MPAA, TV Parental Guidelines).
	ContentRating OptString `json:"contentRating"`
}

// GetType returns the value of Type.
func (s *Episode) GetType() EpisodeType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Episode) GetID() string {
	return s.ID
}

// GetEpisodeNumber returns the value of EpisodeNumber.
func (s *Episode) GetEpisodeNumber() int {
	return s.EpisodeNumber
}

// GetName returns the value of Name.
func (s *Episode) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Episode) GetDescription() OptString {
	return s.Description
}

// GetDatePublished returns the value of DatePublished.
func (s *Episode) GetDatePublished() OptDate {
	return s.DatePublished
}

// GetDuration returns the value of Duration.
func (s *Episode) GetDuration() string {
	return s.Duration
}

// GetCountryOfOrigin returns the value of CountryOfOrigin.
func (s *Episode) GetCountryOfOrigin() OptString {
	return s.CountryOfOrigin
}

// GetLanguages returns the value of Languages.
func (s *Episode) GetLanguages() []string {
	return s.Languages
}

// GetPoster returns the value of Poster.
func (s *Episode) GetPoster() OptURI {
	return s.Poster
}

// GetContentRating returns the value of ContentRating.
func (s *Episode) GetContentRating() OptString {
	return s.ContentRating
}

// SetType sets the value of Type.
func (s *Episode) SetType(val EpisodeType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Episode) SetID(val string) {
	s.ID = val
}

// SetEpisodeNumber sets the value of EpisodeNumber.
func (s *Episode) SetEpisodeNumber(val int) {
	s.EpisodeNumber = val
}

// SetName sets the value of Name.
func (s *Episode) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Episode) SetDescription(val OptString) {
	s.Description = val
}

// SetDatePublished sets the value of DatePublished.
func (s *Episode) SetDatePublished(val OptDate) {
	s.DatePublished = val
}

// SetDuration sets the value of Duration.
func (s *Episode) SetDuration(val string) {
	s.Duration = val
}

// SetCountryOfOrigin sets the value of CountryOfOrigin.
func (s *Episode) SetCountryOfOrigin(val OptString) {
	s.CountryOfOrigin = val
}

// SetLanguages sets the value of Languages.
func (s *Episode) SetLanguages(val []string) {
	s.Languages = val
}

// SetPoster sets the value of Poster.
func (s *Episode) SetPoster(val OptURI) {
	s.Poster = val
}

// SetContentRating sets the value of ContentRating.
func (s *Episode) SetContentRating(val OptString) {
	s.ContentRating = val
}

func (*Episode) getEpisodeByIdRes() {}

// JSON-LD type discriminator.
type EpisodeType string

const (
	EpisodeTypeTVEpisode EpisodeType = "TVEpisode"
)

// AllValues returns all EpisodeType values.
func (EpisodeType) AllValues() []EpisodeType {
	return []EpisodeType{
		EpisodeTypeTVEpisode,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EpisodeType) MarshalText() ([]byte, error) {
	switch s {
	case EpisodeTypeTVEpisode:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EpisodeType) UnmarshalText(data []byte) error {
	switch EpisodeType(data) {
	case EpisodeTypeTVEpisode:
		*s = EpisodeTypeTVEpisode
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// An error response.
// Ref: #/components/schemas/Error
type Error struct {
	// Machine-readable error code.
	Code string `json:"code"`
	// Human-readable error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getEpisodeThumbnailRes() {}
func (*Error) getMovieBackdropRes()    {}
func (*Error) getMoviePosterRes()      {}
func (*Error) getSeasonBackdropRes()   {}
func (*Error) getSeasonPosterRes()     {}
func (*Error) getSeriesBackdropRes()   {}
func (*Error) getSeriesPosterRes()     {}
func (*Error) getServiceByTagRes()     {}
func (*Error) globalSearchRes()        {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type GetEpisodeByIdBadRequest Error

func (*GetEpisodeByIdBadRequest) getEpisodeByIdRes() {}

type GetEpisodeByIdNotFound Error

func (*GetEpisodeByIdNotFound) getEpisodeByIdRes() {}

type GetEpisodeDASHInitBadRequest Error

func (*GetEpisodeDASHInitBadRequest) getEpisodeDASHInitRes() {}

type GetEpisodeDASHInitNotFound Error

func (*GetEpisodeDASHInitNotFound) getEpisodeDASHInitRes() {}

type GetEpisodeDASHInitOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeDASHInitOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeDASHInitOK) getEpisodeDASHInitRes() {}

type GetEpisodeDASHSegmentBadRequest Error

func (*GetEpisodeDASHSegmentBadRequest) getEpisodeDASHSegmentRes() {}

type GetEpisodeDASHSegmentNotFound Error

func (*GetEpisodeDASHSegmentNotFound) getEpisodeDASHSegmentRes() {}

type GetEpisodeDASHSegmentOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeDASHSegmentOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeDASHSegmentOK) getEpisodeDASHSegmentRes() {}

type GetEpisodeHLSKeyBadRequest Error

func (*GetEpisodeHLSKeyBadRequest) getEpisodeHLSKeyRes() {}

type GetEpisodeHLSKeyNotFound Error

func (*GetEpisodeHLSKeyNotFound) getEpisodeHLSKeyRes() {}

type GetEpisodeHLSKeyOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSKeyOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSKeyOK) getEpisodeHLSKeyRes() {}

type GetEpisodeHLSPartialBadRequest Error

func (*GetEpisodeHLSPartialBadRequest) getEpisodeHLSPartialRes() {}

type GetEpisodeHLSPartialNotFound Error

func (*GetEpisodeHLSPartialNotFound) getEpisodeHLSPartialRes() {}

type GetEpisodeHLSPartialOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSPartialOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSPartialOKVideoMP4) getEpisodeHLSPartialRes() {}

type GetEpisodeHLSPartialOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSPartialOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSPartialOKVideoMp2t) getEpisodeHLSPartialRes() {}

type GetEpisodeHLSPreloadHintBadRequest Error

func (*GetEpisodeHLSPreloadHintBadRequest) getEpisodeHLSPreloadHintRes() {}

type GetEpisodeHLSPreloadHintNotFound Error

func (*GetEpisodeHLSPreloadHintNotFound) getEpisodeHLSPreloadHintRes() {}

type GetEpisodeHLSPreloadHintOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSPreloadHintOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSPreloadHintOKVideoMP4) getEpisodeHLSPreloadHintRes() {}

type GetEpisodeHLSPreloadHintOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSPreloadHintOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSPreloadHintOKVideoMp2t) getEpisodeHLSPreloadHintRes() {}

type GetEpisodeHLSRenditionBadRequest Error

func (*GetEpisodeHLSRenditionBadRequest) getEpisodeHLSRenditionRes() {}

type GetEpisodeHLSRenditionNotFound Error

func (*GetEpisodeHLSRenditionNotFound) getEpisodeHLSRenditionRes() {}

type GetEpisodeHLSRenditionOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSRenditionOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSRenditionOK) getEpisodeHLSRenditionRes() {}

type GetEpisodeHLSRenditionSegmentBadRequest Error

func (*GetEpisodeHLSRenditionSegmentBadRequest) getEpisodeHLSRenditionSegmentRes() {}

type GetEpisodeHLSRenditionSegmentNotFound Error

func (*GetEpisodeHLSRenditionSegmentNotFound) getEpisodeHLSRenditionSegmentRes() {}

type GetEpisodeHLSRenditionSegmentOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSRenditionSegmentOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSRenditionSegmentOKVideoMP4) getEpisodeHLSRenditionSegmentRes() {}

type GetEpisodeHLSRenditionSegmentOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSRenditionSegmentOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSRenditionSegmentOKVideoMp2t) getEpisodeHLSRenditionSegmentRes() {}

type GetEpisodeHLSSessionDataBadRequest Error

func (*GetEpisodeHLSSessionDataBadRequest) getEpisodeHLSSessionDataRes() {}

type GetEpisodeHLSSessionDataNotFound Error

func (*GetEpisodeHLSSessionDataNotFound) getEpisodeHLSSessionDataRes() {}

type GetEpisodeHLSSessionDataOKApplicationJSON string

func (*GetEpisodeHLSSessionDataOKApplicationJSON) getEpisodeHLSSessionDataRes() {}

type GetEpisodeHLSSessionDataOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSSessionDataOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSSessionDataOKTextPlain) getEpisodeHLSSessionDataRes() {}

type GetEpisodeHLSSessionKeyBadRequest Error

func (*GetEpisodeHLSSessionKeyBadRequest) getEpisodeHLSSessionKeyRes() {}

type GetEpisodeHLSSessionKeyNotFound Error

func (*GetEpisodeHLSSessionKeyNotFound) getEpisodeHLSSessionKeyRes() {}

type GetEpisodeHLSSessionKeyOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSSessionKeyOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSSessionKeyOK) getEpisodeHLSSessionKeyRes() {}

type GetEpisodeHLSSteeringBadRequest Error

func (*GetEpisodeHLSSteeringBadRequest) getEpisodeHLSSteeringRes() {}

type GetEpisodeHLSSteeringNotFound Error

func (*GetEpisodeHLSSteeringNotFound) getEpisodeHLSSteeringRes() {}

type GetEpisodeHLSSteeringOKApplicationJSON string

func (*GetEpisodeHLSSteeringOKApplicationJSON) getEpisodeHLSSteeringRes() {}

type GetEpisodeHLSSteeringOKApplicationVndAppleMpegurl struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSSteeringOKApplicationVndAppleMpegurl) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSSteeringOKApplicationVndAppleMpegurl) getEpisodeHLSSteeringRes() {}

type GetEpisodeHLSVariantBadRequest Error

func (*GetEpisodeHLSVariantBadRequest) getEpisodeHLSVariantRes() {}

type GetEpisodeHLSVariantNotFound Error

func (*GetEpisodeHLSVariantNotFound) getEpisodeHLSVariantRes() {}

type GetEpisodeHLSVariantOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSVariantOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSVariantOK) getEpisodeHLSVariantRes() {}

type GetEpisodeHLSVariantSegmentBadRequest Error

func (*GetEpisodeHLSVariantSegmentBadRequest) getEpisodeHLSVariantSegmentRes() {}

type GetEpisodeHLSVariantSegmentNotFound Error

func (*GetEpisodeHLSVariantSegmentNotFound) getEpisodeHLSVariantSegmentRes() {}

type GetEpisodeHLSVariantSegmentOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSVariantSegmentOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSVariantSegmentOKVideoMP4) getEpisodeHLSVariantSegmentRes() {}

type GetEpisodeHLSVariantSegmentOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeHLSVariantSegmentOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeHLSVariantSegmentOKVideoMp2t) getEpisodeHLSVariantSegmentRes() {}

type GetEpisodeStreamFileBadRequest Error

func (*GetEpisodeStreamFileBadRequest) getEpisodeStreamFileRes() {}

type GetEpisodeStreamFileNotFound Error

func (*GetEpisodeStreamFileNotFound) getEpisodeStreamFileRes() {}

type GetEpisodeStreamFileOKApplicationDashXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeStreamFileOKApplicationDashXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeStreamFileOKApplicationDashXML) getEpisodeStreamFileRes() {}

type GetEpisodeStreamFileOKApplicationVndAppleMpegurl struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeStreamFileOKApplicationVndAppleMpegurl) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeStreamFileOKApplicationVndAppleMpegurl) getEpisodeStreamFileRes() {}

type GetEpisodeStreamFileOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeStreamFileOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeStreamFileOKVideoMP4) getEpisodeStreamFileRes() {}

type GetEpisodeStreamsBadRequest Error

func (*GetEpisodeStreamsBadRequest) getEpisodeStreamsRes() {}

type GetEpisodeStreamsNotFound Error

func (*GetEpisodeStreamsNotFound) getEpisodeStreamsRes() {}

type GetEpisodeSubtitleBadRequest Error

func (*GetEpisodeSubtitleBadRequest) getEpisodeSubtitleRes() {}

type GetEpisodeSubtitleNotFound Error

func (*GetEpisodeSubtitleNotFound) getEpisodeSubtitleRes() {}

type GetEpisodeSubtitleOKApplicationTtmlXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeSubtitleOKApplicationTtmlXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeSubtitleOKApplicationTtmlXML) getEpisodeSubtitleRes() {}

type GetEpisodeSubtitleOKApplicationXSubrip struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeSubtitleOKApplicationXSubrip) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeSubtitleOKApplicationXSubrip) getEpisodeSubtitleRes() {}

type GetEpisodeSubtitleOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeSubtitleOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeSubtitleOKTextPlain) getEpisodeSubtitleRes() {}

type GetEpisodeSubtitleOKTextVtt struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeSubtitleOKTextVtt) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeSubtitleOKTextVtt) getEpisodeSubtitleRes() {}

type GetEpisodeSubtitlesBadRequest Error

func (*GetEpisodeSubtitlesBadRequest) getEpisodeSubtitlesRes() {}

type GetEpisodeSubtitlesNotFound Error

func (*GetEpisodeSubtitlesNotFound) getEpisodeSubtitlesRes() {}

type GetEpisodeThumbnailOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeThumbnailOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeThumbnailOKImageJpeg) getEpisodeThumbnailRes() {}

type GetEpisodeThumbnailOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeThumbnailOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeThumbnailOKImagePNG) getEpisodeThumbnailRes() {}

type GetEpisodeThumbnailOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetEpisodeThumbnailOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetEpisodeThumbnailOKImageWEBP) getEpisodeThumbnailRes() {}

type GetEpisodesBadRequest Error

func (*GetEpisodesBadRequest) getEpisodesRes() {}

type GetEpisodesNotFound Error

func (*GetEpisodesNotFound) getEpisodesRes() {}

type GetMovieBackdropOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieBackdropOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieBackdropOKImageJpeg) getMovieBackdropRes() {}

type GetMovieBackdropOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieBackdropOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieBackdropOKImagePNG) getMovieBackdropRes() {}

type GetMovieBackdropOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieBackdropOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieBackdropOKImageWEBP) getMovieBackdropRes() {}

type GetMovieByIdBadRequest Error

func (*GetMovieByIdBadRequest) getMovieByIdRes() {}

type GetMovieByIdNotFound Error

func (*GetMovieByIdNotFound) getMovieByIdRes() {}

type GetMovieDASHInitBadRequest Error

func (*GetMovieDASHInitBadRequest) getMovieDASHInitRes() {}

type GetMovieDASHInitNotFound Error

func (*GetMovieDASHInitNotFound) getMovieDASHInitRes() {}

type GetMovieDASHInitOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieDASHInitOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieDASHInitOK) getMovieDASHInitRes() {}

type GetMovieDASHSegmentBadRequest Error

func (*GetMovieDASHSegmentBadRequest) getMovieDASHSegmentRes() {}

type GetMovieDASHSegmentNotFound Error

func (*GetMovieDASHSegmentNotFound) getMovieDASHSegmentRes() {}

type GetMovieDASHSegmentOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieDASHSegmentOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieDASHSegmentOK) getMovieDASHSegmentRes() {}

type GetMovieHLSKeyBadRequest Error

func (*GetMovieHLSKeyBadRequest) getMovieHLSKeyRes() {}

type GetMovieHLSKeyNotFound Error

func (*GetMovieHLSKeyNotFound) getMovieHLSKeyRes() {}

type GetMovieHLSKeyOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSKeyOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSKeyOK) getMovieHLSKeyRes() {}

type GetMovieHLSPartialBadRequest Error

func (*GetMovieHLSPartialBadRequest) getMovieHLSPartialRes() {}

type GetMovieHLSPartialNotFound Error

func (*GetMovieHLSPartialNotFound) getMovieHLSPartialRes() {}

type GetMovieHLSPartialOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSPartialOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSPartialOKVideoMP4) getMovieHLSPartialRes() {}

type GetMovieHLSPartialOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSPartialOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSPartialOKVideoMp2t) getMovieHLSPartialRes() {}

type GetMovieHLSPreloadHintBadRequest Error

func (*GetMovieHLSPreloadHintBadRequest) getMovieHLSPreloadHintRes() {}

type GetMovieHLSPreloadHintNotFound Error

func (*GetMovieHLSPreloadHintNotFound) getMovieHLSPreloadHintRes() {}

type GetMovieHLSPreloadHintOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSPreloadHintOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSPreloadHintOKVideoMP4) getMovieHLSPreloadHintRes() {}

type GetMovieHLSPreloadHintOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSPreloadHintOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSPreloadHintOKVideoMp2t) getMovieHLSPreloadHintRes() {}

type GetMovieHLSRenditionBadRequest Error

func (*GetMovieHLSRenditionBadRequest) getMovieHLSRenditionRes() {}

type GetMovieHLSRenditionNotFound Error

func (*GetMovieHLSRenditionNotFound) getMovieHLSRenditionRes() {}

type GetMovieHLSRenditionOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSRenditionOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSRenditionOK) getMovieHLSRenditionRes() {}

type GetMovieHLSRenditionSegmentBadRequest Error

func (*GetMovieHLSRenditionSegmentBadRequest) getMovieHLSRenditionSegmentRes() {}

type GetMovieHLSRenditionSegmentNotFound Error

func (*GetMovieHLSRenditionSegmentNotFound) getMovieHLSRenditionSegmentRes() {}

type GetMovieHLSRenditionSegmentOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSRenditionSegmentOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSRenditionSegmentOKVideoMP4) getMovieHLSRenditionSegmentRes() {}

type GetMovieHLSRenditionSegmentOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSRenditionSegmentOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSRenditionSegmentOKVideoMp2t) getMovieHLSRenditionSegmentRes() {}

type GetMovieHLSSessionDataBadRequest Error

func (*GetMovieHLSSessionDataBadRequest) getMovieHLSSessionDataRes() {}

type GetMovieHLSSessionDataNotFound Error

func (*GetMovieHLSSessionDataNotFound) getMovieHLSSessionDataRes() {}

type GetMovieHLSSessionDataOKApplicationJSON string

func (*GetMovieHLSSessionDataOKApplicationJSON) getMovieHLSSessionDataRes() {}

type GetMovieHLSSessionDataOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSSessionDataOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSSessionDataOKTextPlain) getMovieHLSSessionDataRes() {}

type GetMovieHLSSessionKeyBadRequest Error

func (*GetMovieHLSSessionKeyBadRequest) getMovieHLSSessionKeyRes() {}

type GetMovieHLSSessionKeyNotFound Error

func (*GetMovieHLSSessionKeyNotFound) getMovieHLSSessionKeyRes() {}

type GetMovieHLSSessionKeyOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSSessionKeyOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSSessionKeyOK) getMovieHLSSessionKeyRes() {}

type GetMovieHLSSteeringBadRequest Error

func (*GetMovieHLSSteeringBadRequest) getMovieHLSSteeringRes() {}

type GetMovieHLSSteeringNotFound Error

func (*GetMovieHLSSteeringNotFound) getMovieHLSSteeringRes() {}

type GetMovieHLSSteeringOKApplicationJSON string

func (*GetMovieHLSSteeringOKApplicationJSON) getMovieHLSSteeringRes() {}

type GetMovieHLSSteeringOKApplicationVndAppleMpegurl struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSSteeringOKApplicationVndAppleMpegurl) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSSteeringOKApplicationVndAppleMpegurl) getMovieHLSSteeringRes() {}

type GetMovieHLSVariantBadRequest Error

func (*GetMovieHLSVariantBadRequest) getMovieHLSVariantRes() {}

type GetMovieHLSVariantNotFound Error

func (*GetMovieHLSVariantNotFound) getMovieHLSVariantRes() {}

type GetMovieHLSVariantOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSVariantOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSVariantOK) getMovieHLSVariantRes() {}

type GetMovieHLSVariantSegmentBadRequest Error

func (*GetMovieHLSVariantSegmentBadRequest) getMovieHLSVariantSegmentRes() {}

type GetMovieHLSVariantSegmentNotFound Error

func (*GetMovieHLSVariantSegmentNotFound) getMovieHLSVariantSegmentRes() {}

type GetMovieHLSVariantSegmentOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSVariantSegmentOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSVariantSegmentOKVideoMP4) getMovieHLSVariantSegmentRes() {}

type GetMovieHLSVariantSegmentOKVideoMp2t struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieHLSVariantSegmentOKVideoMp2t) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieHLSVariantSegmentOKVideoMp2t) getMovieHLSVariantSegmentRes() {}

type GetMoviePosterOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMoviePosterOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMoviePosterOKImageJpeg) getMoviePosterRes() {}

type GetMoviePosterOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMoviePosterOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMoviePosterOKImagePNG) getMoviePosterRes() {}

type GetMoviePosterOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMoviePosterOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMoviePosterOKImageWEBP) getMoviePosterRes() {}

type GetMovieStreamFileBadRequest Error

func (*GetMovieStreamFileBadRequest) getMovieStreamFileRes() {}

type GetMovieStreamFileNotFound Error

func (*GetMovieStreamFileNotFound) getMovieStreamFileRes() {}

type GetMovieStreamFileOKApplicationDashXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieStreamFileOKApplicationDashXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieStreamFileOKApplicationDashXML) getMovieStreamFileRes() {}

type GetMovieStreamFileOKApplicationVndAppleMpegurl struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieStreamFileOKApplicationVndAppleMpegurl) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieStreamFileOKApplicationVndAppleMpegurl) getMovieStreamFileRes() {}

type GetMovieStreamFileOKVideoMP4 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieStreamFileOKVideoMP4) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieStreamFileOKVideoMP4) getMovieStreamFileRes() {}

type GetMovieStreamsBadRequest Error

func (*GetMovieStreamsBadRequest) getMovieStreamsRes() {}

type GetMovieStreamsNotFound Error

func (*GetMovieStreamsNotFound) getMovieStreamsRes() {}

type GetMovieSubtitleBadRequest Error

func (*GetMovieSubtitleBadRequest) getMovieSubtitleRes() {}

type GetMovieSubtitleNotFound Error

func (*GetMovieSubtitleNotFound) getMovieSubtitleRes() {}

type GetMovieSubtitleOKApplicationTtmlXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieSubtitleOKApplicationTtmlXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieSubtitleOKApplicationTtmlXML) getMovieSubtitleRes() {}

type GetMovieSubtitleOKApplicationXSubrip struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieSubtitleOKApplicationXSubrip) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieSubtitleOKApplicationXSubrip) getMovieSubtitleRes() {}

type GetMovieSubtitleOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieSubtitleOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieSubtitleOKTextPlain) getMovieSubtitleRes() {}

type GetMovieSubtitleOKTextVtt struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetMovieSubtitleOKTextVtt) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetMovieSubtitleOKTextVtt) getMovieSubtitleRes() {}

type GetMovieSubtitlesBadRequest Error

func (*GetMovieSubtitlesBadRequest) getMovieSubtitlesRes() {}

type GetMovieSubtitlesNotFound Error

func (*GetMovieSubtitlesNotFound) getMovieSubtitlesRes() {}

type GetMoviesBadRequest Error

func (*GetMoviesBadRequest) getMoviesRes() {}

type GetMoviesNotFound Error

func (*GetMoviesNotFound) getMoviesRes() {}

type GetSeasonBackdropOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeasonBackdropOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeasonBackdropOKImageJpeg) getSeasonBackdropRes() {}

type GetSeasonBackdropOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeasonBackdropOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeasonBackdropOKImagePNG) getSeasonBackdropRes() {}

type GetSeasonBackdropOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeasonBackdropOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeasonBackdropOKImageWEBP) getSeasonBackdropRes() {}

type GetSeasonByIdBadRequest Error

func (*GetSeasonByIdBadRequest) getSeasonByIdRes() {}

type GetSeasonByIdNotFound Error

func (*GetSeasonByIdNotFound) getSeasonByIdRes() {}

type GetSeasonPosterOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeasonPosterOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeasonPosterOKImageJpeg) getSeasonPosterRes() {}

type GetSeasonPosterOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeasonPosterOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeasonPosterOKImagePNG) getSeasonPosterRes() {}

type GetSeasonPosterOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeasonPosterOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeasonPosterOKImageWEBP) getSeasonPosterRes() {}

type GetSeasonsBadRequest Error

func (*GetSeasonsBadRequest) getSeasonsRes() {}

type GetSeasonsNotFound Error

func (*GetSeasonsNotFound) getSeasonsRes() {}

type GetSeriesBackdropOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeriesBackdropOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeriesBackdropOKImageJpeg) getSeriesBackdropRes() {}

type GetSeriesBackdropOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeriesBackdropOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeriesBackdropOKImagePNG) getSeriesBackdropRes() {}

type GetSeriesBackdropOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeriesBackdropOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeriesBackdropOKImageWEBP) getSeriesBackdropRes() {}

type GetSeriesBadRequest Error

func (*GetSeriesBadRequest) getSeriesRes() {}

type GetSeriesByIdBadRequest Error

func (*GetSeriesByIdBadRequest) getSeriesByIdRes() {}

type GetSeriesByIdNotFound Error

func (*GetSeriesByIdNotFound) getSeriesByIdRes() {}

type GetSeriesNotFound Error

func (*GetSeriesNotFound) getSeriesRes() {}

type GetSeriesPosterOKImageJpeg struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeriesPosterOKImageJpeg) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeriesPosterOKImageJpeg) getSeriesPosterRes() {}

type GetSeriesPosterOKImagePNG struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeriesPosterOKImagePNG) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeriesPosterOKImagePNG) getSeriesPosterRes() {}

type GetSeriesPosterOKImageWEBP struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetSeriesPosterOKImageWEBP) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetSeriesPosterOKImageWEBP) getSeriesPosterRes() {}

// Represents the current operational status of the API.
// Ref: #/components/schemas/Health
type Health struct {
	//  - `ok`: All systems operational.
	//  - `degraded`: Functional but with reduced capacity.
	//  - `down`: API is not serving requests.
	Status HealthStatus `json:"status"`
	// Current API version string.
	Version OptString `json:"version"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *Health) GetVersion() OptString {
	return s.Version
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *Health) SetVersion(val OptString) {
	s.Version = val
}

// - `ok`: All systems operational.
// - `degraded`: Functional but with reduced capacity.
// - `down`: API is not serving requests.
type HealthStatus string

const (
	HealthStatusOk       HealthStatus = "ok"
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusDown     HealthStatus = "down"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
		HealthStatusDegraded,
		HealthStatusDown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	case HealthStatusDegraded:
		return []byte(s), nil
	case HealthStatusDown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	case HealthStatusDegraded:
		*s = HealthStatusDegraded
		return nil
	case HealthStatusDown:
		*s = HealthStatusDown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A self-contained film with no seasonal divisions. Maps to schema.org [Movie].
//
// [Movie]: https://schema.org/Movie
// Ref: #/components/schemas/Movie
type Movie struct {
	// JSON-LD type discriminator.
	Type MovieType `json:"@type"`
	// Canonical API identifier (path-safe slug).
	ID string `json:"id"`
	// Title of the movie.
	Name string `json:"name"`
	// Plot summary or tagline.
	Description OptString `json:"description"`
	// Original release date (ISO 8601 / RFC 3339 full-date).
	DatePublished OptDate `json:"datePublished"`
	// Runtime in ISO 8601 duration format.
	Duration OptString `json:"duration"`
	// ISO 3166-1 alpha-2 country code of origin.
	CountryOfOrigin OptString `json:"countryOfOrigin"`
	// ISO 639-1 language codes available in this movie's audio or subtitles.
	Languages []string `json:"languages"`
	// Content rating from the source country's rating system (e.g. MPAA, TV Parental Guidelines).
	ContentRating OptString `json:"contentRating"`
	// One or more genre classifications.
	Genres []string `json:"genres"`
	// URL to the movie poster image.
	Poster OptURI `json:"poster"`
	// URL to the movie backdrop image.
	Backdrop OptURI `json:"backdrop"`
	// URL to a trailer video.
	Trailer OptURI `json:"trailer"`
}

// GetType returns the value of Type.
func (s *Movie) GetType() MovieType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Movie) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Movie) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Movie) GetDescription() OptString {
	return s.Description
}

// GetDatePublished returns the value of DatePublished.
func (s *Movie) GetDatePublished() OptDate {
	return s.DatePublished
}

// GetDuration returns the value of Duration.
func (s *Movie) GetDuration() OptString {
	return s.Duration
}

// GetCountryOfOrigin returns the value of CountryOfOrigin.
func (s *Movie) GetCountryOfOrigin() OptString {
	return s.CountryOfOrigin
}

// GetLanguages returns the value of Languages.
func (s *Movie) GetLanguages() []string {
	return s.Languages
}

// GetContentRating returns the value of ContentRating.
func (s *Movie) GetContentRating() OptString {
	return s.ContentRating
}

// GetGenres returns the value of Genres.
func (s *Movie) GetGenres() []string {
	return s.Genres
}

// GetPoster returns the value of Poster.
func (s *Movie) GetPoster() OptURI {
	return s.Poster
}

// GetBackdrop returns the value of Backdrop.
func (s *Movie) GetBackdrop() OptURI {
	return s.Backdrop
}

// GetTrailer returns the value of Trailer.
func (s *Movie) GetTrailer() OptURI {
	return s.Trailer
}

// SetType sets the value of Type.
func (s *Movie) SetType(val MovieType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Movie) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Movie) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Movie) SetDescription(val OptString) {
	s.Description = val
}

// SetDatePublished sets the value of DatePublished.
func (s *Movie) SetDatePublished(val OptDate) {
	s.DatePublished = val
}

// SetDuration sets the value of Duration.
func (s *Movie) SetDuration(val OptString) {
	s.Duration = val
}

// SetCountryOfOrigin sets the value of CountryOfOrigin.
func (s *Movie) SetCountryOfOrigin(val OptString) {
	s.CountryOfOrigin = val
}

// SetLanguages sets the value of Languages.
func (s *Movie) SetLanguages(val []string) {
	s.Languages = val
}

// SetContentRating sets the value of ContentRating.
func (s *Movie) SetContentRating(val OptString) {
	s.ContentRating = val
}

// SetGenres sets the value of Genres.
func (s *Movie) SetGenres(val []string) {
	s.Genres = val
}

// SetPoster sets the value of Poster.
func (s *Movie) SetPoster(val OptURI) {
	s.Poster = val
}

// SetBackdrop sets the value of Backdrop.
func (s *Movie) SetBackdrop(val OptURI) {
	s.Backdrop = val
}

// SetTrailer sets the value of Trailer.
func (s *Movie) SetTrailer(val OptURI) {
	s.Trailer = val
}

func (*Movie) getMovieByIdRes() {}

// JSON-LD type discriminator.
type MovieType string

const (
	MovieTypeMovie MovieType = "Movie"
)

// AllValues returns all MovieType values.
func (MovieType) AllValues() []MovieType {
	return []MovieType{
		MovieTypeMovie,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MovieType) MarshalText() ([]byte, error) {
	switch s {
	case MovieTypeMovie:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MovieType) UnmarshalText(data []byte) error {
	switch MovieType(data) {
	case MovieTypeMovie:
		*s = MovieTypeMovie
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceType returns new OptServiceType with value set to v.
func NewOptServiceType(v ServiceType) OptServiceType {
	return OptServiceType{
		Value: v,
		Set:   true,
	}
}

// OptServiceType is optional ServiceType.
type OptServiceType struct {
	Value ServiceType
	Set   bool
}

// IsSet returns true if OptServiceType was set.
func (o OptServiceType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceType) Reset() {
	var v ServiceType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceType) SetTo(v ServiceType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceType) Get() (v ServiceType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceType) Or(d ServiceType) ServiceType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSubtitleKind returns new OptSubtitleKind with value set to v.
func NewOptSubtitleKind(v SubtitleKind) OptSubtitleKind {
	return OptSubtitleKind{
		Value: v,
		Set:   true,
	}
}

// OptSubtitleKind is optional SubtitleKind.
type OptSubtitleKind struct {
	Value SubtitleKind
	Set   bool
}

// IsSet returns true if OptSubtitleKind was set.
func (o OptSubtitleKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSubtitleKind) Reset() {
	var v SubtitleKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSubtitleKind) SetTo(v SubtitleKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSubtitleKind) Get() (v SubtitleKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSubtitleKind) Or(d SubtitleKind) SubtitleKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Paginated list of episodes.
// Ref: #/components/schemas/Page_Episode
type PageEpisode struct {
	Items  []Episode `json:"items"`
	Total  int       `json:"total"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageEpisode) GetItems() []Episode {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageEpisode) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageEpisode) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageEpisode) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageEpisode) SetItems(val []Episode) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageEpisode) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageEpisode) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageEpisode) SetOffset(val int) {
	s.Offset = val
}

func (*PageEpisode) getEpisodesRes() {}

// Paginated list of movies.
// Ref: #/components/schemas/Page_Movie
type PageMovie struct {
	Items  []Movie `json:"items"`
	Total  int     `json:"total"`
	Limit  int     `json:"limit"`
	Offset int     `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageMovie) GetItems() []Movie {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageMovie) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageMovie) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageMovie) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageMovie) SetItems(val []Movie) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageMovie) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageMovie) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageMovie) SetOffset(val int) {
	s.Offset = val
}

func (*PageMovie) getMoviesRes() {}

// Paginated list of search results.
// Ref: #/components/schemas/Page_SearchResult
type PageSearchResult struct {
	Items  []SearchResultItem `json:"items"`
	Total  int                `json:"total"`
	Limit  int                `json:"limit"`
	Offset int                `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageSearchResult) GetItems() []SearchResultItem {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageSearchResult) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageSearchResult) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageSearchResult) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageSearchResult) SetItems(val []SearchResultItem) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageSearchResult) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageSearchResult) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageSearchResult) SetOffset(val int) {
	s.Offset = val
}

func (*PageSearchResult) globalSearchRes() {}

// Paginated list of seasons.
// Ref: #/components/schemas/Page_Season
type PageSeason struct {
	Items  []Season `json:"items"`
	Total  int      `json:"total"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageSeason) GetItems() []Season {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageSeason) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageSeason) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageSeason) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageSeason) SetItems(val []Season) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageSeason) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageSeason) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageSeason) SetOffset(val int) {
	s.Offset = val
}

func (*PageSeason) getSeasonsRes() {}

// Paginated list of TV series.
// Ref: #/components/schemas/Page_Series
type PageSeries struct {
	Items  []Series `json:"items"`
	Total  int      `json:"total"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageSeries) GetItems() []Series {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageSeries) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageSeries) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageSeries) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageSeries) SetItems(val []Series) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageSeries) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageSeries) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageSeries) SetOffset(val int) {
	s.Offset = val
}

func (*PageSeries) getSeriesRes() {}

// Paginated list of streaming services.
// Ref: #/components/schemas/Page_Service
type PageService struct {
	Items []Service `json:"items"`
	// Total number of matching items across all pages.
	Total int `json:"total"`
	// Maximum items per page (as requested).
	Limit int `json:"limit"`
	// Zero-based offset of the first item in this page.
	Offset int `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageService) GetItems() []Service {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageService) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageService) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageService) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageService) SetItems(val []Service) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageService) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageService) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageService) SetOffset(val int) {
	s.Offset = val
}

// Paginated list of video stream manifests.
// Ref: #/components/schemas/Page_Stream
type PageStream struct {
	Items  []Stream `json:"items"`
	Total  int      `json:"total"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageStream) GetItems() []Stream {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageStream) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageStream) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageStream) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageStream) SetItems(val []Stream) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageStream) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageStream) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageStream) SetOffset(val int) {
	s.Offset = val
}

func (*PageStream) getEpisodeStreamsRes() {}
func (*PageStream) getMovieStreamsRes()   {}

// Paginated list of external subtitle files.
// Ref: #/components/schemas/Page_Subtitle
type PageSubtitle struct {
	Items  []Subtitle `json:"items"`
	Total  int        `json:"total"`
	Limit  int        `json:"limit"`
	Offset int        `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageSubtitle) GetItems() []Subtitle {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageSubtitle) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageSubtitle) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageSubtitle) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageSubtitle) SetItems(val []Subtitle) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageSubtitle) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageSubtitle) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageSubtitle) SetOffset(val int) {
	s.Offset = val
}

func (*PageSubtitle) getEpisodeSubtitlesRes() {}
func (*PageSubtitle) getMovieSubtitlesRes()   {}

// A single item returned from a global search query.
// Ref: #/components/schemas/SearchResultItem
type SearchResultItem struct {
	// Relevance score (higher is more relevant).
	Score    float32                  `json:"score"`
	Resource SearchResultItemResource `json:"resource"`
}

// GetScore returns the value of Score.
func (s *SearchResultItem) GetScore() float32 {
	return s.Score
}

// GetResource returns the value of Resource.
func (s *SearchResultItem) GetResource() SearchResultItemResource {
	return s.Resource
}

// SetScore sets the value of Score.
func (s *SearchResultItem) SetScore(val float32) {
	s.Score = val
}

// SetResource sets the value of Resource.
func (s *SearchResultItem) SetResource(val SearchResultItemResource) {
	s.Resource = val
}

// SearchResultItemResource represents sum type.
type SearchResultItemResource struct {
	// Type selects the active sum variant, switch on this field.
	Type    SearchResultItemResourceType
	Service Service
	Movie   Movie
	Series  Series
}

// SearchResultItemResourceType is oneOf type of SearchResultItemResource.
type SearchResultItemResourceType string

// Possible values for SearchResultItemResourceType.
const (
	ServiceSearchResultItemResource SearchResultItemResourceType = "Service"
	MovieSearchResultItemResource   SearchResultItemResourceType = "Movie"
	SeriesSearchResultItemResource  SearchResultItemResourceType = "TVSeries"
)

// IsService reports whether SearchResultItemResource is Service.
func (s SearchResultItemResource) IsService() bool { return s.Type == ServiceSearchResultItemResource }

// IsMovie reports whether SearchResultItemResource is Movie.
func (s SearchResultItemResource) IsMovie() bool { return s.Type == MovieSearchResultItemResource }

// IsSeries reports whether SearchResultItemResource is Series.
func (s SearchResultItemResource) IsSeries() bool { return s.Type == SeriesSearchResultItemResource }

// SetService sets SearchResultItemResource to Service.
func (s *SearchResultItemResource) SetService(v Service) {
	s.Type = ServiceSearchResultItemResource
	s.Service = v
}

// GetService returns Service and true boolean if SearchResultItemResource is Service.
func (s SearchResultItemResource) GetService() (v Service, ok bool) {
	if !s.IsService() {
		return v, false
	}
	return s.Service, true
}

// NewServiceSearchResultItemResource returns new SearchResultItemResource from Service.
func NewServiceSearchResultItemResource(v Service) SearchResultItemResource {
	var s SearchResultItemResource
	s.SetService(v)
	return s
}

// SetMovie sets SearchResultItemResource to Movie.
func (s *SearchResultItemResource) SetMovie(v Movie) {
	s.Type = MovieSearchResultItemResource
	s.Movie = v
}

// GetMovie returns Movie and true boolean if SearchResultItemResource is Movie.
func (s SearchResultItemResource) GetMovie() (v Movie, ok bool) {
	if !s.IsMovie() {
		return v, false
	}
	return s.Movie, true
}

// NewMovieSearchResultItemResource returns new SearchResultItemResource from Movie.
func NewMovieSearchResultItemResource(v Movie) SearchResultItemResource {
	var s SearchResultItemResource
	s.SetMovie(v)
	return s
}

// SetSeries sets SearchResultItemResource to Series.
func (s *SearchResultItemResource) SetSeries(v Series) {
	s.Type = SeriesSearchResultItemResource
	s.Series = v
}

// GetSeries returns Series and true boolean if SearchResultItemResource is Series.
func (s SearchResultItemResource) GetSeries() (v Series, ok bool) {
	if !s.IsSeries() {
		return v, false
	}
	return s.Series, true
}

// NewSeriesSearchResultItemResource returns new SearchResultItemResource from Series.
func NewSeriesSearchResultItemResource(v Series) SearchResultItemResource {
	var s SearchResultItemResource
	s.SetSeries(v)
	return s
}

type SearchTypeItem string

const (
	SearchTypeItemService SearchTypeItem = "service"
	SearchTypeItemMovie   SearchTypeItem = "movie"
	SearchTypeItemSeries  SearchTypeItem = "series"
)

// AllValues returns all SearchTypeItem values.
func (SearchTypeItem) AllValues() []SearchTypeItem {
	return []SearchTypeItem{
		SearchTypeItemService,
		SearchTypeItemMovie,
		SearchTypeItemSeries,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SearchTypeItem) MarshalText() ([]byte, error) {
	switch s {
	case SearchTypeItemService:
		return []byte(s), nil
	case SearchTypeItemMovie:
		return []byte(s), nil
	case SearchTypeItemSeries:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SearchTypeItem) UnmarshalText(data []byte) error {
	switch SearchTypeItem(data) {
	case SearchTypeItemService:
		*s = SearchTypeItemService
		return nil
	case SearchTypeItemMovie:
		*s = SearchTypeItemMovie
		return nil
	case SearchTypeItemSeries:
		*s = SearchTypeItemSeries
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A single season within a TV series. Maps to schema.org [TVSeason].
//
// [TVSeason]: https://schema.org/TVSeason
// Ref: #/components/schemas/Season
type Season struct {
	// JSON-LD type discriminator.
	Type SeasonType `json:"@type"`
	// Canonical API identifier.
	ID string `json:"id"`
	// Sequential season number.
	SeasonNumber int `json:"seasonNumber"`
	// Human-readable season name.
	Name string `json:"name"`
	// Description of the season's narrative arc.
	Description OptString `json:"description"`
	// Season premiere date (ISO 8601 / RFC 3339 full-date).
	DatePublished OptDate `json:"datePublished"`
	// ISO 3166-1 alpha-2 country code of origin.
	CountryOfOrigin OptString `json:"countryOfOrigin"`
	// ISO 639-1 language codes available in this season.
	Languages []string `json:"languages"`
	// URL to the season's poster or cover art.
	Poster OptURI `json:"poster"`
	// URL to the season's backdrop image.
	Backdrop OptURI `json:"backdrop"`
	// Total number of episodes in this season.
	NumberOfEpisodes OptInt `json:"numberOfEpisodes"`
	// URL to a season trailer.
	Trailer OptURI `json:"trailer"`
}

// GetType returns the value of Type.
func (s *Season) GetType() SeasonType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Season) GetID() string {
	return s.ID
}

// GetSeasonNumber returns the value of SeasonNumber.
func (s *Season) GetSeasonNumber() int {
	return s.SeasonNumber
}

// GetName returns the value of Name.
func (s *Season) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Season) GetDescription() OptString {
	return s.Description
}

// GetDatePublished returns the value of DatePublished.
func (s *Season) GetDatePublished() OptDate {
	return s.DatePublished
}

// GetCountryOfOrigin returns the value of CountryOfOrigin.
func (s *Season) GetCountryOfOrigin() OptString {
	return s.CountryOfOrigin
}

// GetLanguages returns the value of Languages.
func (s *Season) GetLanguages() []string {
	return s.Languages
}

// GetPoster returns the value of Poster.
func (s *Season) GetPoster() OptURI {
	return s.Poster
}

// GetBackdrop returns the value of Backdrop.
func (s *Season) GetBackdrop() OptURI {
	return s.Backdrop
}

// GetNumberOfEpisodes returns the value of NumberOfEpisodes.
func (s *Season) GetNumberOfEpisodes() OptInt {
	return s.NumberOfEpisodes
}

// GetTrailer returns the value of Trailer.
func (s *Season) GetTrailer() OptURI {
	return s.Trailer
}

// SetType sets the value of Type.
func (s *Season) SetType(val SeasonType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Season) SetID(val string) {
	s.ID = val
}

// SetSeasonNumber sets the value of SeasonNumber.
func (s *Season) SetSeasonNumber(val int) {
	s.SeasonNumber = val
}

// SetName sets the value of Name.
func (s *Season) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Season) SetDescription(val OptString) {
	s.Description = val
}

// SetDatePublished sets the value of DatePublished.
func (s *Season) SetDatePublished(val OptDate) {
	s.DatePublished = val
}

// SetCountryOfOrigin sets the value of CountryOfOrigin.
func (s *Season) SetCountryOfOrigin(val OptString) {
	s.CountryOfOrigin = val
}

// SetLanguages sets the value of Languages.
func (s *Season) SetLanguages(val []string) {
	s.Languages = val
}

// SetPoster sets the value of Poster.
func (s *Season) SetPoster(val OptURI) {
	s.Poster = val
}

// SetBackdrop sets the value of Backdrop.
func (s *Season) SetBackdrop(val OptURI) {
	s.Backdrop = val
}

// SetNumberOfEpisodes sets the value of NumberOfEpisodes.
func (s *Season) SetNumberOfEpisodes(val OptInt) {
	s.NumberOfEpisodes = val
}

// SetTrailer sets the value of Trailer.
func (s *Season) SetTrailer(val OptURI) {
	s.Trailer = val
}

func (*Season) getSeasonByIdRes() {}

// JSON-LD type discriminator.
type SeasonType string

const (
	SeasonTypeTVSeason SeasonType = "TVSeason"
)

// AllValues returns all SeasonType values.
func (SeasonType) AllValues() []SeasonType {
	return []SeasonType{
		SeasonTypeTVSeason,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SeasonType) MarshalText() ([]byte, error) {
	switch s {
	case SeasonTypeTVSeason:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SeasonType) UnmarshalText(data []byte) error {
	switch SeasonType(data) {
	case SeasonTypeTVSeason:
		*s = SeasonTypeTVSeason
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A TV series containing one or more seasons and episodes. Maps to schema.org [TVSeries].
//
// [TVSeries]: https://schema.org/TVSeries
// Ref: #/components/schemas/Series
type Series struct {
	// JSON-LD type discriminator.
	Type SeriesType `json:"@type"`
	// Canonical API identifier (path-safe slug).
	ID string `json:"id"`
	// Title of the series.
	Name string `json:"name"`
	// Plot summary or tagline.
	Description OptString `json:"description"`
	// Original premiere date (ISO 8601 / RFC 3339 full-date).
	DatePublished OptDate `json:"datePublished"`
	// ISO 3166-1 alpha-2 country code of origin.
	CountryOfOrigin OptString `json:"countryOfOrigin"`
	// ISO 639-1 language codes available in this series.
	Languages []string `json:"languages"`
	// Content rating (e.g. MPAA, TV Parental Guidelines).
	ContentRating OptString `json:"contentRating"`
	// One or more genre classifications.
	Genres []string `json:"genres"`
	// URL to the series poster image.
	Poster OptURI `json:"poster"`
	// URL to the series backdrop image.
	Backdrop OptURI `json:"backdrop"`
	// URL to a trailer video.
	Trailer OptURI `json:"trailer"`
	// Total number of seasons currently available.
	NumberOfSeasons int `json:"numberOfSeasons"`
}

// GetType returns the value of Type.
func (s *Series) GetType() SeriesType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Series) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Series) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Series) GetDescription() OptString {
	return s.Description
}

// GetDatePublished returns the value of DatePublished.
func (s *Series) GetDatePublished() OptDate {
	return s.DatePublished
}

// GetCountryOfOrigin returns the value of CountryOfOrigin.
func (s *Series) GetCountryOfOrigin() OptString {
	return s.CountryOfOrigin
}

// GetLanguages returns the value of Languages.
func (s *Series) GetLanguages() []string {
	return s.Languages
}

// GetContentRating returns the value of ContentRating.
func (s *Series) GetContentRating() OptString {
	return s.ContentRating
}

// GetGenres returns the value of Genres.
func (s *Series) GetGenres() []string {
	return s.Genres
}

// GetPoster returns the value of Poster.
func (s *Series) GetPoster() OptURI {
	return s.Poster
}

// GetBackdrop returns the value of Backdrop.
func (s *Series) GetBackdrop() OptURI {
	return s.Backdrop
}

// GetTrailer returns the value of Trailer.
func (s *Series) GetTrailer() OptURI {
	return s.Trailer
}

// GetNumberOfSeasons returns the value of NumberOfSeasons.
func (s *Series) GetNumberOfSeasons() int {
	return s.NumberOfSeasons
}

// SetType sets the value of Type.
func (s *Series) SetType(val SeriesType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Series) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Series) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Series) SetDescription(val OptString) {
	s.Description = val
}

// SetDatePublished sets the value of DatePublished.
func (s *Series) SetDatePublished(val OptDate) {
	s.DatePublished = val
}

// SetCountryOfOrigin sets the value of CountryOfOrigin.
func (s *Series) SetCountryOfOrigin(val OptString) {
	s.CountryOfOrigin = val
}

// SetLanguages sets the value of Languages.
func (s *Series) SetLanguages(val []string) {
	s.Languages = val
}

// SetContentRating sets the value of ContentRating.
func (s *Series) SetContentRating(val OptString) {
	s.ContentRating = val
}

// SetGenres sets the value of Genres.
func (s *Series) SetGenres(val []string) {
	s.Genres = val
}

// SetPoster sets the value of Poster.
func (s *Series) SetPoster(val OptURI) {
	s.Poster = val
}

// SetBackdrop sets the value of Backdrop.
func (s *Series) SetBackdrop(val OptURI) {
	s.Backdrop = val
}

// SetTrailer sets the value of Trailer.
func (s *Series) SetTrailer(val OptURI) {
	s.Trailer = val
}

// SetNumberOfSeasons sets the value of NumberOfSeasons.
func (s *Series) SetNumberOfSeasons(val int) {
	s.NumberOfSeasons = val
}

func (*Series) getSeriesByIdRes() {}

// JSON-LD type discriminator.
type SeriesType string

const (
	SeriesTypeTVSeries SeriesType = "TVSeries"
)

// AllValues returns all SeriesType values.
func (SeriesType) AllValues() []SeriesType {
	return []SeriesType{
		SeriesTypeTVSeries,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SeriesType) MarshalText() ([]byte, error) {
	switch s {
	case SeriesTypeTVSeries:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SeriesType) UnmarshalText(data []byte) error {
	switch SeriesType(data) {
	case SeriesTypeTVSeries:
		*s = SeriesTypeTVSeries
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A streaming service platform (e.g. Netflix, Crave, Disney+). Maps to schema.org [Service].
//
// [Service]: https://schema.org/Service
// Ref: #/components/schemas/Service
type Service struct {
	// JSON-LD type discriminator.
	Type OptServiceType `json:"@type"`
	// Short, unique service identifier.
	Tag string `json:"tag"`
	// Human-readable service name.
	Name string `json:"name"`
	// Short description of the service.
	Description OptString `json:"description"`
	// Official website URL.
	Website OptURI `json:"website"`
	// ISO 3166-1 alpha-2 country code of the service's primary market.
	Country OptString `json:"country"`
	// ISO 639-1 language codes available on this service.
	Languages []string `json:"languages"`
	// URL to the service's logo image.
	Logo OptURI `json:"logo"`
}

// GetType returns the value of Type.
func (s *Service) GetType() OptServiceType {
	return s.Type
}

// GetTag returns the value of Tag.
func (s *Service) GetTag() string {
	return s.Tag
}

// GetName returns the value of Name.
func (s *Service) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Service) GetDescription() OptString {
	return s.Description
}

// GetWebsite returns the value of Website.
func (s *Service) GetWebsite() OptURI {
	return s.Website
}

// GetCountry returns the value of Country.
func (s *Service) GetCountry() OptString {
	return s.Country
}

// GetLanguages returns the value of Languages.
func (s *Service) GetLanguages() []string {
	return s.Languages
}

// GetLogo returns the value of Logo.
func (s *Service) GetLogo() OptURI {
	return s.Logo
}

// SetType sets the value of Type.
func (s *Service) SetType(val OptServiceType) {
	s.Type = val
}

// SetTag sets the value of Tag.
func (s *Service) SetTag(val string) {
	s.Tag = val
}

// SetName sets the value of Name.
func (s *Service) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Service) SetDescription(val OptString) {
	s.Description = val
}

// SetWebsite sets the value of Website.
func (s *Service) SetWebsite(val OptURI) {
	s.Website = val
}

// SetCountry sets the value of Country.
func (s *Service) SetCountry(val OptString) {
	s.Country = val
}

// SetLanguages sets the value of Languages.
func (s *Service) SetLanguages(val []string) {
	s.Languages = val
}

// SetLogo sets the value of Logo.
func (s *Service) SetLogo(val OptURI) {
	s.Logo = val
}

func (*Service) getServiceByTagRes() {}

// JSON-LD type discriminator.
type ServiceType string

const (
	ServiceTypeService ServiceType = "Service"
)

// AllValues returns all ServiceType values.
func (ServiceType) AllValues() []ServiceType {
	return []ServiceType{
		ServiceTypeService,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ServiceType) MarshalText() ([]byte, error) {
	switch s {
	case ServiceTypeService:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ServiceType) UnmarshalText(data []byte) error {
	switch ServiceType(data) {
	case ServiceTypeService:
		*s = ServiceTypeService
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A single video stream manifest or playlist file. Each stream represents one playable artifact using
// a specific streaming technology (DASH, HLS, MP4). Fetch the individual file endpoint to retrieve the
// raw bytes.
//
// Maps to schema.org [VideoObject].
//
// [VideoObject]: https://schema.org/VideoObject
// Ref: #/components/schemas/Stream
type Stream struct {
	// JSON-LD type discriminator.
	Type StreamType `json:"@type"`
	// Stream file identifier matching the path segment. Convention: `manifest.mpd` (DASH), `master.m3u8`
	// (HLS), `video.mp4` (MP4).
	ID string `json:"id"`
	// Human-readable stream label.
	Name string `json:"name"`
	// MIME type identifying the streaming protocol.
	EncodingFormat StreamEncodingFormat `json:"encodingFormat"`
}

// GetType returns the value of Type.
func (s *Stream) GetType() StreamType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Stream) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Stream) GetName() string {
	return s.Name
}

// GetEncodingFormat returns the value of EncodingFormat.
func (s *Stream) GetEncodingFormat() StreamEncodingFormat {
	return s.EncodingFormat
}

// SetType sets the value of Type.
func (s *Stream) SetType(val StreamType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Stream) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Stream) SetName(val string) {
	s.Name = val
}

// SetEncodingFormat sets the value of EncodingFormat.
func (s *Stream) SetEncodingFormat(val StreamEncodingFormat) {
	s.EncodingFormat = val
}

// MIME type identifying the streaming protocol.
type StreamEncodingFormat string

const (
	StreamEncodingFormatApplicationDashXML         StreamEncodingFormat = "application/dash+xml"
	StreamEncodingFormatApplicationVndAppleMpegurl StreamEncodingFormat = "application/vnd.apple.mpegurl"
	StreamEncodingFormatVideoMP4                   StreamEncodingFormat = "video/mp4"
)

// AllValues returns all StreamEncodingFormat values.
func (StreamEncodingFormat) AllValues() []StreamEncodingFormat {
	return []StreamEncodingFormat{
		StreamEncodingFormatApplicationDashXML,
		StreamEncodingFormatApplicationVndAppleMpegurl,
		StreamEncodingFormatVideoMP4,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s StreamEncodingFormat) MarshalText() ([]byte, error) {
	switch s {
	case StreamEncodingFormatApplicationDashXML:
		return []byte(s), nil
	case StreamEncodingFormatApplicationVndAppleMpegurl:
		return []byte(s), nil
	case StreamEncodingFormatVideoMP4:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *StreamEncodingFormat) UnmarshalText(data []byte) error {
	switch StreamEncodingFormat(data) {
	case StreamEncodingFormatApplicationDashXML:
		*s = StreamEncodingFormatApplicationDashXML
		return nil
	case StreamEncodingFormatApplicationVndAppleMpegurl:
		*s = StreamEncodingFormatApplicationVndAppleMpegurl
		return nil
	case StreamEncodingFormatVideoMP4:
		*s = StreamEncodingFormatVideoMP4
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type StreamFormat string

const (
	StreamFormatHls  StreamFormat = "hls"
	StreamFormatDash StreamFormat = "dash"
	StreamFormatMP4  StreamFormat = "mp4"
)

// AllValues returns all StreamFormat values.
func (StreamFormat) AllValues() []StreamFormat {
	return []StreamFormat{
		StreamFormatHls,
		StreamFormatDash,
		StreamFormatMP4,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s StreamFormat) MarshalText() ([]byte, error) {
	switch s {
	case StreamFormatHls:
		return []byte(s), nil
	case StreamFormatDash:
		return []byte(s), nil
	case StreamFormatMP4:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *StreamFormat) UnmarshalText(data []byte) error {
	switch StreamFormat(data) {
	case StreamFormatHls:
		*s = StreamFormatHls
		return nil
	case StreamFormatDash:
		*s = StreamFormatDash
		return nil
	case StreamFormatMP4:
		*s = StreamFormatMP4
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// JSON-LD type discriminator.
type StreamType string

const (
	StreamTypeVideoObject StreamType = "VideoObject"
)

// AllValues returns all StreamType values.
func (StreamType) AllValues() []StreamType {
	return []StreamType{
		StreamTypeVideoObject,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s StreamType) MarshalText() ([]byte, error) {
	switch s {
	case StreamTypeVideoObject:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *StreamType) UnmarshalText(data []byte) error {
	switch StreamType(data) {
	case StreamTypeVideoObject:
		*s = StreamTypeVideoObject
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// An external subtitle file not embedded in any stream manifest. Subtitles that are already part of a
// DASH or HLS manifest are not duplicated here - only standalone sidecar files are listed. At least,
// as long as it's feasable and doesn't require file parsing. If it does, the subtitles might be
// duplicated between the file and here.
//
// Use the individual file endpoint to retrieve the raw content.
// Ref: #/components/schemas/Subtitle
type Subtitle struct {
	// Subtitle id, made up of the first characters hash of the url of the upstream subtitle file.
	ID string `json:"id"`
	// Upstream URL of the subtitle file. May point at the provider's own sidecar endpoint rather than the
	// public media CDN.
	URL OptURI `json:"url"`
	// ISO 639-1 language code.
	Language string `json:"language"`
	// Human-readable language or label.
	Name OptString `json:"name"`
	// Subtitle variant.
	//
	//  - `default`: Standard dialogue subtitles
	//  - `sdh`: Subtitles for the deaf or hard-of-hearing
	//  - `cc`: Closed captions
	//  - `forced`: Forced narration (foreign dialogue, signs)
	Kind OptSubtitleKind `json:"kind"`
	// Subtitle file format.
	Format SubtitleFormat `json:"format"`
	// Whether this subtitle should be auto-enabled by the player.
	IsDefault OptBool `json:"isDefault"`
}

// GetID returns the value of ID.
func (s *Subtitle) GetID() string {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Subtitle) GetURL() OptURI {
	return s.URL
}

// GetLanguage returns the value of Language.
func (s *Subtitle) GetLanguage() string {
	return s.Language
}

// GetName returns the value of Name.
func (s *Subtitle) GetName() OptString {
	return s.Name
}

// GetKind returns the value of Kind.
func (s *Subtitle) GetKind() OptSubtitleKind {
	return s.Kind
}

// GetFormat returns the value of Format.
func (s *Subtitle) GetFormat() SubtitleFormat {
	return s.Format
}

// GetIsDefault returns the value of IsDefault.
func (s *Subtitle) GetIsDefault() OptBool {
	return s.IsDefault
}

// SetID sets the value of ID.
func (s *Subtitle) SetID(val string) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Subtitle) SetURL(val OptURI) {
	s.URL = val
}

// SetLanguage sets the value of Language.
func (s *Subtitle) SetLanguage(val string) {
	s.Language = val
}

// SetName sets the value of Name.
func (s *Subtitle) SetName(val OptString) {
	s.Name = val
}

// SetKind sets the value of Kind.
func (s *Subtitle) SetKind(val OptSubtitleKind) {
	s.Kind = val
}

// SetFormat sets the value of Format.
func (s *Subtitle) SetFormat(val SubtitleFormat) {
	s.Format = val
}

// SetIsDefault sets the value of IsDefault.
func (s *Subtitle) SetIsDefault(val OptBool) {
	s.IsDefault = val
}

// Subtitle file format.
type SubtitleFormat string

const (
	SubtitleFormatVtt  SubtitleFormat = "vtt"
	SubtitleFormatSrt  SubtitleFormat = "srt"
	SubtitleFormatTtml SubtitleFormat = "ttml"
	SubtitleFormatAss  SubtitleFormat = "ass"
)

// AllValues returns all SubtitleFormat values.
func (SubtitleFormat) AllValues() []SubtitleFormat {
	return []SubtitleFormat{
		SubtitleFormatVtt,
		SubtitleFormatSrt,
		SubtitleFormatTtml,
		SubtitleFormatAss,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SubtitleFormat) MarshalText() ([]byte, error) {
	switch s {
	case SubtitleFormatVtt:
		return []byte(s), nil
	case SubtitleFormatSrt:
		return []byte(s), nil
	case SubtitleFormatTtml:
		return []byte(s), nil
	case SubtitleFormatAss:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SubtitleFormat) UnmarshalText(data []byte) error {
	switch SubtitleFormat(data) {
	case SubtitleFormatVtt:
		*s = SubtitleFormatVtt
		return nil
	case SubtitleFormatSrt:
		*s = SubtitleFormatSrt
		return nil
	case SubtitleFormatTtml:
		*s = SubtitleFormatTtml
		return nil
	case SubtitleFormatAss:
		*s = SubtitleFormatAss
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Subtitle variant.
//
//   - `default`: Standard dialogue subtitles
//   - `sdh`: Subtitles for the deaf or hard-of-hearing
//   - `cc`: Closed captions
//   - `forced`: Forced narration (foreign dialogue, signs)
type SubtitleKind string

const (
	SubtitleKindDefault SubtitleKind = "default"
	SubtitleKindSdh     SubtitleKind = "sdh"
	SubtitleKindCc      SubtitleKind = "cc"
	SubtitleKindForced  SubtitleKind = "forced"
)

// AllValues returns all SubtitleKind values.
func (SubtitleKind) AllValues() []SubtitleKind {
	return []SubtitleKind{
		SubtitleKindDefault,
		SubtitleKindSdh,
		SubtitleKindCc,
		SubtitleKindForced,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SubtitleKind) MarshalText() ([]byte, error) {
	switch s {
	case SubtitleKindDefault:
		return []byte(s), nil
	case SubtitleKindSdh:
		return []byte(s), nil
	case SubtitleKindCc:
		return []byte(s), nil
	case SubtitleKindForced:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SubtitleKind) UnmarshalText(data []byte) error {
	switch SubtitleKind(data) {
	case SubtitleKindDefault:
		*s = SubtitleKindDefault
		return nil
	case SubtitleKindSdh:
		*s = SubtitleKindSdh
		return nil
	case SubtitleKindCc:
		*s = SubtitleKindCc
		return nil
	case SubtitleKindForced:
		*s = SubtitleKindForced
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
