FROM node:alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY svelte.config.js ./
COPY tsconfig.json ./
COPY vite.config.ts ./

RUN npm ci

COPY . .

RUN npm run build

#####################################

FROM node:alpine

WORKDIR /srv/www

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=8001

RUN addgroup -S appgroup
RUN adduser -S appuser -G appgroup

ENV PROTOCOL_HEADER=X-Forwarded-Proto
ENV HOST_HEADER=X-Forwarded-Host

COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./

RUN npm ci --omit=dev

USER appuser

CMD ["node", "build"]